### ISSUE TITLE
只要添加support design 库，layout Desgin那里就出现Render Errors

### ISSUE THREAD

**Issue by SawXu** [Jude95/Beam#18]
Android Studio 2.3 Beta 1

报错如下:

java.lang.NoSuchFieldError: ViewBackgroundHelper
	at android.support.v7.widget.AppCompatBackgroundHelper.loadFromAttributes(AppCompatBackgroundHelper.java:46)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:63)
	at android.support.v7.widget.AppCompatImageView.<init>(AppCompatImageView.java:56)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:441)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:240)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:195)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadClass(LayoutlibCallbackImpl.java:193)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:333)
	at android.view.BridgeInflater.onCreateView(BridgeInflater.java:152)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:222)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at com.android.layoutlib.bridge.bars.CustomBar.<init>(CustomBar.java:95)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:52)
	at com.android.layoutlib.bridge.bars.NavigationBar.<init>(NavigationBar.java:46)
	at com.android.layoutlib.bridge.impl.Layout.createNavBar(Layout.java:284)
	at com.android.layoutlib.bridge.impl.Layout.<init>(Layout.java:140)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:301)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SawXu** [comment]
我把Android Studio换成2.2.3稳定版就没有问题了，看来是Android Studio的锅。
